import type { DashboardCopy } from "./dashboard-copy.js";

export const dashboardCopyZhCn = {
  "meta.title": "Embassy — 本地交换记录",
  skip: "跳至 Embassy 状态",
  "language.label": "语言",
  "language.en": "English",
  "language.zhCn": "简体中文",
  "brand.eyebrow": "本地智能体交换",
  "brand.title": "Embassy",
  "brand.subtitle": "Claude Code 与 Codex 路由在一个时间点的仅元数据记录。",
  "snapshot.asOf": "快照时间 {time}",
  "snapshot.static":
    "此文件不会自行更新。运行 embassy refresh-dashboard 后重新加载；或者运行 embassy dashboard --live 查看流式视图。",
  "overall.ready": "交换已就绪",
  "overall.setup": "设置尚未完成",
  "overall.attention": "需要处理",
  "exchange.eyebrow": "交换台",
  "exchange.title": "两个方向，两道明确边界",
  "exchange.note":
    "Codex 只会向已选择的 Claude 会话发送消息。同一操作系统用户下，每个兼容且在线的 Claude 会话都能看到已注册的 Codex 任务。",
  "exchange.claude.title": "Claude 选择",
  "exchange.claude.note": "Codex → Claude 的目标",
  "exchange.codex.title": "Codex 注册",
  "exchange.codex.note": "Claude → Codex 的目标",
  "exchange.pouch.title": "本地信袋",
  "exchange.pouch.empty": "队列为空",
  "exchange.pouch.queued": "{count} 条排队中",
  "exchange.pouch.oldest": "最长等待 {age}",
  "exchange.count.claude":
    "已选择 {ready} · 可选择 {selectable} · 已发现 {total}",
  "exchange.count.codex": "已就绪 {ready} · 已注册 {total}",
  "status.ready": "就绪",
  "status.busy": "忙碌",
  "status.waiting": "等待中",
  "status.missing": "尚未配置",
  "status.attention": "不可用",
  "status.selected": "已选择",
  "status.available": "可用",
  "status.notSelectable": "不可选择",
  "status.enabled": "已启用",
  "status.disabled": "已停用",
  "next.label": "下一步",
  "next.none": "无需操作。",
  "next.discoverClaude":
    "启动或保持一个 Claude Code 会话运行，然后运行 embassy refresh-dashboard。",
  "next.selectClaude":
    "运行 embassy select-claude --alias <alias>，明确选择一个可见会话。",
  "next.restoreClaude": "刷新发现；若未自动恢复，请明确选择 Claude 当前别名。",
  "next.repairClaude":
    "当前没有兼容、在线且无冲突的可选会话。请先解决“会话与路由”中显示的问题，再刷新发现。",
  "next.registerCodex":
    "在 Codex 任务内运行 embassy register-codex --alias codex-<name>@<host>。",
  "next.restoreCodex":
    "在该 Codex 任务内重新运行 embassy register-codex --alias <alias>。",
  "attention.eyebrow": "需要处理",
  "attention.title": "发送前请先解决",
  "attention.count": "{count} 项",
  "attention.countVisible": "显示 {count} 项",
  "attention.projectionOnly":
    "面板投影前省略了其他警告元数据。请查看有界显示说明并运行 embassy status。",
  "attention.scope": "范围",
  "severity.info": "信息",
  "severity.warning": "警告",
  "severity.error": "错误",
  "guidance.reobserveClaude.title": "需要重新观察 Claude 选择",
  "guidance.reobserveClaude.body": "已保存路由目前没有匹配的在线端点证明。",
  "guidance.reobserveClaude.action": "刷新发现并明确选择 Claude 当前别名。",
  "guidance.reobserveCodex.title": "需要重新观察 Codex 注册",
  "guidance.reobserveCodex.body": "已保存路由目前没有匹配的在线端点证明。",
  "guidance.reobserveCodex.action": "在该 Codex 任务内重新运行 register-codex。",
  "guidance.claudeNotObserved.title": "已选择的 Claude 会话不可见",
  "guidance.claudeNotObserved.body": "当前本地发现中没有该会话。",
  "guidance.claudeNotObserved.action":
    "保持 Claude 运行并启用 crossSessionInbound，刷新后选择其当前别名。",
  "guidance.codexStale.title": "Codex 路由需要重新观察",
  "guidance.codexStale.body": "已注册的 Codex 任务不再具有就绪的 App Server 连接。",
  "guidance.codexStale.action":
    "在该 Codex 任务内使用同一别名重新运行 register-codex；不要先注销。",
  "guidance.connectorOffline.title": "提供方连接器离线",
  "guidance.connectorOffline.body": "Embassy 当前无法访问本地提供方连接器。",
  "guidance.connectorOffline.action":
    "运行 embassy status。仅当排队消息和活跃投递均为零时才能重启；重启会放弃仅存于内存的消息正文。",
  "guidance.routeStale.title": "路由需要重新观察",
  "guidance.routeStale.body": "该路由不再具有当前端点证明。",
  "guidance.routeStale.action": "刷新并恢复相应选择或注册。",
  "guidance.queueStalled.title": "排队投递停滞",
  "guidance.queueStalled.body": "最早接受的消息已排队超过投递截止时间的一半。",
  "guidance.queueStalled.action":
    "运行 embassy status。不要重发已接受的工作；Embassy 会跟踪到结算或过期。",
  "guidance.unconfirmed.title": "无法确认投递",
  "guidance.unconfirmed.body":
    "本地传输写入已完成，但该次尝试结算时没有可用的终结原生证据。",
  "guidance.unconfirmed.action": "重试前检查接收方；重试可能造成重复消息。",
  "guidance.degraded.title": "交换状态降级",
  "guidance.degraded.body": "Embassy 保留了一条规范化的兼容性或连接器警告。",
  "guidance.degraded.action":
    "运行 embassy status。仅当排队消息和活跃投递均为零时才能重启；重启会放弃仅存于内存的消息正文。",
  "guidance.generic.title": "Embassy 报告了规范化警告",
  "guidance.generic.body": "面板没有为此安全代码映射自动修复方案。",
  "guidance.generic.action": "检查 embassy status。绝不要自动重试结果不确定的投递。",
  "guidance.codexSuccessionBusy.title": "更换 Codex 任务需要等待静默边界",
  "guidance.codexSuccessionBusy.body":
    "由于已接受或正在进行的工作尚未完全排空，Embassy 保留了当前 Codex 注册。",
  "guidance.codexSuccessionBusy.action":
    "等待当前工作进入终结状态，运行 embassy status，然后重试同一条 register-codex --alias <new> --succeeds <old> 命令。",
  "guidance.codexSuccessionRecovery.title": "更换 Codex 任务需要手动恢复",
  "guidance.codexSuccessionRecovery.body":
    "任务更换未能到达安全的活跃代次。Embassy 会让 Codex 注册保持离线，而不会猜测哪个任务拥有路由。",
  "guidance.codexSuccessionRecovery.action":
    "请勿发送消息、重试任务更换或假定任一任务处于活跃状态。运行 embassy status，并保留当前状态以供手动恢复。",
  "transit.eyebrow": "传输中",
  "transit.title": "队列状态",
  "transit.queued": "排队消息",
  "transit.active": "活跃投递",
  "transit.oldest": "最长排队时间",
  "transit.empty": "快照时没有排队消息。",
  "transit.unavailable": "时间戳不可用",
  "count.atLeast": "至少 {count}",
  "activity.eyebrow": "活动记录",
  "activity.title": "最近投递证据",
  "activity.note": "绝不包含正文或提供方内部数据。",
  "activity.empty": "尚未记录投递元数据。",
  "activity.column.updated": "更新时间",
  "activity.column.route": "路由",
  "activity.column.id": "编号",
  "activity.column.result": "结果",
  "activity.column.elapsed": "耗时",
  "activity.column.size": "大小",
  "activity.column.history": "证据",
  "activity.history.one": "1 个阶段",
  "activity.history.many": "{count} 个阶段",
  "activity.meaning.delivered":
    "已达到 delivered 终局状态。这不表示模型已经读取或处理该消息。",
  "activity.meaning.delivered.codexToClaude":
    "Claude 返回了终结 released 回执：消息已进入接收方队列。这不表示模型已经读取或处理该消息。",
  "activity.meaning.delivered.claudeToCodex":
    "Codex App Server 已接受该轮输入。这不表示模型已经完成或处理该输入。",
  "activity.meaning.unconfirmed":
    "传输写入已完成，但终结原生证据不可用。重试前请检查接收方。",
  "activity.meaning.ambiguous": "不确定写入后的结果未知。请勿自动重试。",
  "activity.meaning.other": "这是最新的规范化投递状态。",
  "activity.meaning.queued": "已接收并在本地队列中等待。是进行中，不代表成功。",
  "activity.meaning.dispatching":
    "正在移交给接收端连接器。是进行中，不代表成功。",
  "activity.meaning.transportWritten":
    "已写入接收方传输通道，最终回执尚未到达。是进行中，不代表成功。",
  "activity.meaning.held": "写入已完成；接收方在其审批闸门后暂挂处理。",
  "activity.meaning.duplicate": "与已接收消息重复。本条从未被接收。",
  "activity.meaning.rejected":
    "在接收前被拒绝——例如截止时间无效或队列已满。它从未进入队列。",
  "activity.meaning.failed":
    "已按失败终局。安全代码说明原因；切勿自动重试结果不确定的投递。",
  "activity.meaning.expired": "在观察到任何传输写入之前，投递截止时间已过。",
  "activity.meaning.cancelled": "在终局前被明确取消。",
  "activity.meaning.abandoned.controllerRestarted":
    "broker 在终局前停止——属设计行为；重启之间不转移任何内容。",
  "activity.meaning.abandoned.transientBody":
    "内存中的消息正文在派发前已不可用。",
  "activity.meaning.abandoned.routeTerminated": "其路由在投递终局前被注销。",
  "activity.meaning.abandoned.generic": "在完成前按放弃终局；详见安全代码。",
  "direction.claudeToCodex": "Claude → Codex",
  "direction.codexToClaude": "Codex → Claude",
  "delivery.queued": "已排队",
  "delivery.duplicate": "重复",
  "delivery.dispatching": "正在投递",
  "delivery.transportWritten": "已写入传输层",
  "delivery.held": "已暂存",
  "delivery.delivered": "已投递",
  "delivery.unconfirmed": "未确认",
  "delivery.failed": "失败",
  "delivery.ambiguous": "结果不确定",
  "delivery.expired": "已超出投递期限",
  "delivery.cancelled": "已取消",
  "delivery.abandoned": "已放弃",
  "delivery.rejected": "已拒绝",
  "sessions.eyebrow": "会话与路由",
  "sessions.title": "登记簿",
  "sessions.note": "仅显示公开别名；原生标识符已省略。",
  "sessions.peers.title": "已发现的 Claude 会话",
  "sessions.peers.empty": "此快照中没有可见的 Claude 会话。",
  "sessions.peers.caption": "已发现的 Claude 会话及选择状态",
  "sessions.routes.title": "消息路由",
  "sessions.routes.empty": "尚未注册或选择路由。",
  "sessions.routes.caption": "已注册及已选择的消息路由",
  "column.alias": "别名",
  "column.host": "主机",
  "column.provider": "提供方",
  "column.state": "状态",
  "column.compatibility": "兼容性",
  "column.selection": "选择",
  "column.queue": "队列",
  "column.observed": "观察时间",
  "column.issue": "问题",
  "diagnostics.title": "兼容性与系统详情",
  "diagnostics.note": "固定协议、计数器与有界显示说明",
  "diagnostics.connectors": "连接器",
  "diagnostics.connectors.empty": "没有连接器元数据。",
  "diagnostics.connectors.caption": "本地提供方连接器状态",
  "diagnostics.protocol": "协议",
  "diagnostics.health": "健康状态",
  "diagnostics.accounting": "计数快照",
  "diagnostics.accepted": "已接受",
  "diagnostics.duplicates": "重复项",
  "diagnostics.delivered": "已投递",
  "diagnostics.unconfirmed": "未确认",
  "diagnostics.ambiguous": "结果不确定",
  "diagnostics.failed": "失败",
  "diagnostics.expired": "超出投递期限",
  "diagnostics.cancelled": "已取消",
  "diagnostics.abandoned": "已放弃",
  "diagnostics.rejected": "已拒绝",
  "diagnostics.bytesAccepted": "已接受字节",
  "diagnostics.queuedBytes": "排队字节",
  "diagnostics.omissions": "有界显示",
  "diagnostics.omissions.none": "没有省略内容。",
  "diagnostics.omissions.connectors": "{count} 个连接器",
  "diagnostics.omissions.peers": "{count} 个会话",
  "diagnostics.omissions.routes": "{count} 条路由",
  "diagnostics.omissions.upstreamMessageEvents":
    "面板投影前的 {count} 条投递事件",
  "diagnostics.omissions.messageGroups": "{count} 组投递",
  "diagnostics.omissions.messageEvents": "{count} 条证据记录",
  "diagnostics.omissions.upstreamAlerts": "面板投影前的 {count} 个警告",
  "diagnostics.omissions.attentionItems": "{count} 个待处理项",
  "provider.claude": "Claude",
  "provider.codex": "Codex",
  "health.offline": "离线",
  "health.connecting": "连接中",
  "health.healthy": "健康",
  "health.degraded": "降级",
  "health.incompatible": "不兼容",
  "health.meaning.healthy": "已连接并在交换心跳。",
  "health.meaning.connecting": "正在建立本地连接。",
  "health.meaning.degraded": "已连接，但保留了警告。",
  "health.meaning.offline": "在本机上无法访问。",
  "health.meaning.incompatible": "版本握手失败。",
  "compatibility.unknown": "未知",
  "compatibility.compatible": "兼容",
  "compatibility.incompatible": "不兼容",
  "compatibility.expired": "兼容性观察已失效",
  "compatibility.meaning.compatible": "已按固定的版本范围校验通过。",
  "compatibility.meaning.unknown": "尚未校验。",
  "compatibility.meaning.expired": "校验已失效；请重新观察。",
  "compatibility.meaning.incompatible": "超出受支持的版本范围。",
  "route.stale": "已过时",
  "route.idle": "空闲",
  "route.busy": "忙碌",
  "route.awaitingApproval": "等待批准",
  "route.offline": "离线",
  "route.incompatible": "不兼容",
  "route.disabled": "已停用",
  "route.meaning.idle": "已启用、兼容，可以承载消息。",
  "route.meaning.busy": "正在承载一轮消息；新消息会进入队列。",
  "route.meaning.awaitingApproval": "正在等待提供方的原生审批。",
  "route.meaning.stale": "当前没有端点证明；请刷新并恢复该路由。",
  "route.meaning.offline": "该路由的连接器无法访问。",
  "route.meaning.incompatible": "协议版本不匹配。",
  "route.meaning.disabled": "已被管理性停用，不属于故障。",
  "peer.idle": "空闲",
  "peer.busy": "忙碌",
  "peer.awaitingApproval": "等待批准",
  "peer.offline": "离线",
  "peer.incompatible": "不兼容",
  "peer.meaning.idle": "在线且可选择。",
  "peer.meaning.busy": "在线，但正处于一轮对话中。",
  "peer.meaning.awaitingApproval": "正在等待原生审批。",
  "peer.meaning.offline": "此前已发现，当前不在线——是候选项，不是错误。",
  "peer.meaning.incompatible": "无法选择：协议不兼容。",
  "peer.reason.aliasCollision": "别名冲突：请重命名其中一个 Claude 会话，然后刷新发现。",
  "peer.reason.sessionCollision":
    "会话标识冲突：请关闭重复的会话记录，然后刷新发现。",
  "peer.reason.discoveryIncomplete":
    "发现结果不完整。请等待 Claude Code 完成会话清单发布后再刷新。",
  "peer.reason.incompatible": "此会话与 Embassy 固定的协议版本不兼容。",
  "peer.reason.offline": "此会话当前不在线。",
  "time.atSnapshot": "快照时",
  "time.beforeSnapshot": "快照前 {age}",
  "time.afterSnapshot": "快照后 {age}",
  "time.unavailable": "—",
  "time.ago": "{duration}前",
  "live.title": "Embassy — 实时面板",
  "live.noscript":
    "此实时视图需要 JavaScript。状态目录中的静态 gateway-dashboard.html 仍为离线底线。",
  "live.label": "实时伴侣",
  "live.mastheadSubtitle": "只读实时元数据流。serve 仍限套接字通道。",
  "live.readonlyFooter":
    "此视图无权执行 register、select、send、reply、approve 或 interrupt。",
  "live.connection.connecting": "正在连接…",
  "live.connection.connected": "数据流已连接",
  "live.connection.unavailable": "观察器不可用 — 正在重试",
  "live.connection.disconnected": "连接已断开 — 请点击“重新连接”",
  "live.connection.fatal": "面板会话不可用",
  "live.connection.paused": "更新已暂停",
  "live.connection.stopped": "面板已停止",
  "live.control.pause": "暂停",
  "live.control.reconnect": "重新连接",
  "live.control.refresh": "立即读取",
  "live.filter.placeholder": "筛选别名与活动",
  "live.metric.queued": "排队中",
  "live.metric.active": "活跃",
  "live.attention.empty": "当前没有需要处理的项目。",
  "live.activity.empty": "尚无投递元数据。",
  "live.sessions.title": "会话",
  "live.diagnostics.title": "诊断",
  "live.metric.revision": "流版本",
  "live.stream.reset": "来源已重启；视图已重新同步。",
  "live.bootstrap.title": "打开 Embassy 实时面板",
  "live.bootstrap.open": "打开 Embassy 实时面板",
  "live.http.badRequest": "请求无效。",
  "live.http.forbidden": "禁止访问。",
  "live.http.notFound": "未找到。",
  "live.http.methodNotAllowed": "不允许使用此方法。",
  "live.http.bodyTooLarge": "请求正文过大。",
  "live.http.targetTooLarge": "请求目标过长。",
  "live.http.unsupportedMediaType": "不支持此媒体类型。",
  "live.http.tooManyStreams": "实时流数量过多。",
  "live.http.headersTooLarge": "请求头过大。",
  "live.http.snapshotUnavailable": "面板快照不可用。",
  "live.http.requestFailed": "请求失败。",
  "live.http.starting": "面板正在启动。",
  "app.tab.overview": "总览",
  "app.tab.deliveries": "投递",
  "app.tab.routes": "路由与会话",
  "app.tab.activity": "活动",
  "app.tab.diagnostics": "诊断",
  "app.search.label": "搜索别名、消息后缀与安全代码",
  "app.search.placeholder": "搜索 — 回车打开“投递”",
  "app.asOf": "截至 {time}",
  "app.stale": "已有 {age} 未收到新帧，页面所示可能已不是当前状态。",
  "app.missedFrames": "有数据帧丢失。视图已按当前快照重新读取。",
  "app.lowerBound": "至少 {count}；显示数量有上限。",
  "app.readonly": "只读",
  "app.copy": "复制",
  "app.copied": "已复制",
  "app.copyFailed": "复制失败——请手动选择文本",
  "app.staleQuiet": "连接正常；已有 {age} 无任何变化。",
  "app.notLanded.title": "此版本尚未提供",
  "app.notLanded.body":
    "实时契约还没有承载这项内容，因此这里没有可点击的控件。请改用下面的命令。",
  "app.show": "展开",
  "app.hide": "收起",
  "app.overview.statusStrip": "系统状态",
  "app.overview.broker": "Broker",
  "app.overview.claudeConn": "Claude 连接器",
  "app.overview.codexConn": "Codex 连接器",
  "app.overview.compat": "兼容性",
  "app.overview.connectorMissing": "未报告连接器",
  "app.overview.node.claude.title": "claude",
  "app.overview.node.claude.sub": "会话",
  "app.overview.node.codex.title": "codex",
  "app.overview.node.codex.sub": "任务",
  "app.overview.count.codex":
    "已就绪 {ready} · 已注册 {total} · 仅监控 {monitorOnly}",
  "app.overview.noPair.title": "无配对",
  "app.overview.noPair.body":
    "有一侧尚未就绪，消息无法通过。请选择一个 Claude 会话并注册一个 Codex 任务，这条连线才会出现。",
  "app.overview.queueC2x": "Claude → Codex",
  "app.overview.queueX2c": "Claude ← Codex",
  "app.overview.depth": "深度",
  "app.overview.oldest": "最长等待",
  "app.overview.pulse.title": "活动脉冲 — 终局状态，最近一小时",
  "app.overview.pulse.caption": "仅统计已保留的投递分组；更早的证据已被丢弃。",
  "app.overview.pulse.empty": "最近一小时没有投递达成终局。",
  "app.overview.viewIn": "在“投递”中查看",
  "app.deliveries.title": "投递",
  "app.deliveries.caption": "已保留的投递分组，最新在前",
  "app.deliveries.dir.label": "方向",
  "app.deliveries.dir.all": "全部",
  "app.deliveries.dir.codexToClaude": "Claude ← Codex",
  "app.deliveries.view.label": "视图",
  "app.deliveries.view.byRoute": "按路由对",
  "app.deliveries.view.flat": "平铺列表",
  "app.deliveries.state.all": "全部",
  "app.deliveries.search": "搜索后缀、别名或安全代码",
  "app.deliveries.noMatch": "没有符合此筛选条件的投递。可用以下命令发送一条",
  "app.deliveries.pickRow": "选择一条投递以追踪其生命周期。",
  "app.deliveries.lifecycle": "生命周期",
  "app.deliveries.frames": "诊断帧",
  "app.deliveries.noFrames": "此投递没有记录任何安全代码。",
  "app.deliveries.raw": "原始 JSON",
  "app.deliveries.hideRaw": "隐藏原始 JSON",
  "app.deliveries.bodyLabel": "消息正文",
  "app.deliveries.bodiesNote": "正文从不保留——这里只有元数据。",
  "app.deliveries.noConv":
    "实时契约不携带会话标识，因此投递按路由对分组，而不是按会话线索分组。",
  "app.deliveries.eventsTruncated": "有 {count} 条较早的状态变化因保留额度被丢弃。",
  "app.deliveries.earliestRetained": "最早保留的事件",
  "app.routes.topology": "同意拓扑",
  "app.routes.candidates": "候选项",
  "app.routes.claudeSessions": "Claude 会话",
  "app.routes.codexRoutes": "Codex 任务",
  "app.routes.selectCmd.title": "选择 Claude 会话",
  "app.routes.selectCmd.consequence":
    "只有完成选择，Codex 才能发往 Claude。有且只有一个已选择的会话会接收 Codex → Claude 消息。",
  "app.routes.unselectCmd.consequence":
    "取消选择会停止 Codex → Claude 的投递。Claude → Codex 不受影响。",
  "app.routes.refreshCmd": "重新读取本地发现结果，并重写静态面板文件。",
  "app.routes.monitorOnlyReason":
    "仅监控——此路由因 CODEX_WRITES_DISABLED 而停用写入。",
  "app.routes.noPeers": "此快照中没有发现任何 Claude 会话。",
  "app.routes.noCodex": "尚未注册任何 Codex 任务。",
  "app.routes.successions": "继任历史",
  "app.routes.successions.empty": "当前没有正在进行的任务更换。",
  "app.routes.successions.note":
    "任务更换只是把别名移交给新的 Codex 任务。不转移任何内容：排队的工作、历史与审批都留在旧任务上。",
  "app.routes.detail.absent": "实时契约不携带此信息。",
  "app.routes.queueDepth": "队列深度",
  "app.routes.counters": "路由计数器",
  "app.routes.registered": "已注册",
  "app.routes.monitorOnly": "monitor-only",
  "app.routes.registerHint":
    "注册不是按钮：它必须在 Codex 任务内运行以继承其身份。请让你的代理运行：",
  "app.routes.noPairInline":
    "无配对 — 在选择会话之前，任务不接受任何入站消息",
  "app.activity.title": "事件流 — 有界，最新在前",
  "app.activity.kinds.all": "所有类型",
  "app.activity.kinds.delivery": "投递",
  "app.activity.kinds.alert": "警告",
  "app.activity.limited":
    "这里只记录投递终局与警告。发现、选择、任务更换与操作者动作在实时契约中没有对应记录。",
  "app.activity.empty":
    "此窗口内没有内容。事件会随 broker 产生而出现；可以试试",
  "app.diag.versions": "连接器协议",
  "app.diag.versions.caption": "本地连接器的协议与兼容性状态",
  "app.diag.col.provider": "提供方",
  "app.diag.col.host": "主机",
  "app.diag.col.protocol": "协议",
  "app.diag.col.version": "版本",
  "app.diag.col.compat": "兼容性",
  "app.diag.versions.rangeAbsent":
    "实时契约不携带受支持的协议范围，因此这里只显示兼容性判定。",
  "app.diag.attestation.title": "证明",
  "app.diag.attestation.absent":
    "实时契约不携带证明信息。请用下面的命令查看本地状态。",
  "app.diag.lease.title": "租约 / 实例",
  "app.diag.lease.absent": "实时契约不携带租约状态。请用下面的命令查看本地状态。",
  "app.diag.limits": "限制与压力",
  "app.diag.limits.hint":
    "实时契约不公开当前配置值。请设置该环境变量，然后重新启动 embassy serve。",
  "app.diag.deadline.title": "投递截止时间",
  "app.diag.deadline.body":
    "自本次 broker 启动以来，已有 {count} 条投递超出截止时间。",
  "app.diag.queue.title": "队列深度",
  "app.diag.queue.body": "当前有 {count} 条消息在排队。",
  "app.diag.bytes.title": "消息字节预算",
  "app.diag.bytes.body":
    "当前排队 {queued}；自本次 broker 启动以来共接受 {accepted}。",
  "app.diag.steering.title": "转向（steering）",
  "app.diag.steering.absent":
    "STEER 标记表示已分类的 Claude→Codex 投递证据。此元数据契约不公开操作员停用开关的当前设置。",
  "app.diag.editable.title": "设置",
  "app.diag.editable.note":
    "设置在 embassy serve 启动时从环境变量读取。此页面无法修改它们，因此不会把它们显示为可编辑控件。",
  "app.diag.counters": "计数器",
  "app.diag.counters.caption": "本次 broker 进程的累计计数器",
  "app.diag.omissions": "有界显示",
  "app.diag.omissions.caption": "按类别统计的显示前省略行数",
  footer: "只读元数据快照。无脚本、修改控件、外部资源、遥测或网络请求。",
} satisfies DashboardCopy;
