import type { DashboardCopy } from "./dashboard-copy.js";

export const dashboardCopyZhCn = {
  "meta.title": "Embassy — 本地交换记录",
  skip: "跳至 Embassy 状态",
  "language.label": "语言",
  "language.en": "English",
  "language.zhCn": "简体中文",
  "brand.eyebrow": "本地智能体交换",
  "brand.title": "Embassy",
  "brand.subtitle": "本地智能体提供方路由在一个时间点的仅元数据记录。",
  "snapshot.asOf": "快照时间 {time}",
  "snapshot.static":
    "此文件不会自行更新。如果代理未运行，请先运行 embassy serve。然后运行 embassy refresh-dashboard 并重新加载；或者运行 embassy dashboard --live 查看流式视图。",
  "overall.ready": "交换已就绪",
  "overall.setup": "设置尚未完成",
  "overall.attention": "需要处理",
  "exchange.eyebrow": "交换台",
  "exchange.title": "提供方路由与明确边界",
  "exchange.note":
    "每条同意边都指定两个已验证的提供方端点。原生发现仍覆盖整台机器，权限则不会。",
  "inbound.paired.badge": "配对入站",
  "inbound.paired.body": "每个已注册端点只接受沿其显式同意边发送的消息。",
  "inbound.open.badge": "开放入站",
  "inbound.open.body": "提供方允许的同一用户在线端点都可发起入站工作；显式发送仍需同意边。",
  "inbound.noPair.body": "当前没有同意边；配对模式会拒绝未配对发送方。",
  "exchange.claude.title": "Claude 会话",
  "exchange.claude.note": "同意边端点",
  "exchange.codex.title": "Codex 任务",
  "exchange.codex.note": "同意边端点",
  "exchange.provider.note": "同意边端点",
  "exchange.pouch.title": "本地信袋",
  "exchange.pouch.empty": "队列为空",
  "exchange.pouch.queued": "{count} 条排队中",
  "exchange.pouch.oldest": "最长等待 {age}",
  "exchange.count.claude":
    "已选择 {ready} · 可选择 {selectable} · 已发现 {total}",
  "exchange.count.codex": "已就绪 {ready} · 已注册 {total}",
  "app.overview.count.provider": "已就绪 {ready} · 已注册 {total}",
  "status.ready": "就绪",
  "status.busy": "忙碌",
  "status.waiting": "等待中",
  "status.missing": "尚未配置",
  "status.attention": "不可用",
  "status.selected": "已选择",
  "status.available": "可用",
  "status.notSelectable": "不可选择",
  "status.enabled": "已启用",
  "status.disabled": "已停用",
  "next.label": "下一步",
  "next.none": "无需操作。",
  "next.discoverClaude":
    "启动或保持一个 Claude Code 会话运行，然后运行 embassy refresh-dashboard。",
  "next.selectClaude":
    "运行 embassy select-claude --alias <alias>，明确选择一个可见会话。",
  "next.pairRoutes":
    "运行 embassy pair --from <alias> --to <alias>，建立显式同意边。",
  "next.restoreClaude": "刷新发现；若未自动恢复，请明确选择 Claude 当前别名。",
  "next.repairClaude":
    "当前没有在线且无冲突的可选会话。请先解决“会话与路由”中显示的问题，再刷新发现。",
  "next.registerCodex":
    "在 Codex 任务内运行 embassy register-codex --alias codex-<name>@<host>。",
  "next.restoreCodex":
    "在该 Codex 任务内重新运行 embassy register-codex --alias <alias>。",
  "attention.eyebrow": "需要处理",
  "attention.title": "发送前请先解决",
  "attention.count": "{count} 项",
  "attention.countVisible": "显示 {count} 项",
  "attention.projectionOnly":
    "面板投影前省略了其他警告元数据。请查看有界显示说明并运行 embassy status。",
  "attention.scope": "范围",
  "severity.info": "信息",
  "severity.warning": "警告",
  "severity.error": "错误",
  "guidance.reobserveClaude.title": "需要重新观察 Claude 选择",
  "guidance.reobserveClaude.body": "已保存路由目前没有匹配的在线端点证明。",
  "guidance.reobserveClaude.action": "刷新发现并明确选择 Claude 当前别名。",
  "guidance.reobserveCodex.title": "需要重新观察 Codex 注册",
  "guidance.reobserveCodex.body": "已保存路由目前没有匹配的在线端点证明。",
  "guidance.reobserveCodex.action": "在该 Codex 任务内重新运行 register-codex。",
  "guidance.codexReactivationRequired.title": "已保存的 Codex 路由不在线",
  "guidance.codexReactivationRequired.body":
    "同意边仍然保留，但已保存的 Codex 路由当前没有在线端点证明。",
  "guidance.codexReactivationRequired.action":
    "在该 Codex 任务内运行 embassy register-codex --alias {alias}。",
  "guidance.consentEdgeUnavailable.title": "同意边端点不可用",
  "guidance.consentEdgeUnavailable.body":
    "同意边仍然保留，但当前有界快照中缺少这个已保存端点。",
  "guidance.consentEdgeUnavailable.action":
    "请先运行 embassy refresh-dashboard。如果端点仍然缺失，请恢复“范围”中显示的确切端点；无需重建同意边。",
  "guidance.claudeNotObserved.title": "已选择的 Claude 会话不可见",
  "guidance.claudeNotObserved.body": "当前本地发现中没有该会话。",
  "guidance.claudeNotObserved.action":
    "保持 Claude 运行并启用 crossSessionInbound，刷新后选择其当前别名。",
  "guidance.codexStale.title": "Codex 路由需要重新观察",
  "guidance.codexStale.body": "已注册的 Codex 任务不再具有就绪的 App Server 连接。",
  "guidance.codexStale.action":
    "在该 Codex 任务内使用同一别名重新运行 register-codex；不要先注销。",
  "guidance.codexAppReconnectRequired.title": "正在等待 Codex 应用重新连接",
  "guidance.codexAppReconnectRequired.body":
    "托管 App Server 可以访问，但仍观察不到这个已保存任务；应用或任务可能尚未重新连接。",
  "guidance.codexAppReconnectRequired.action":
    "打开 Codex 应用和这个确切任务。如果守护进程重启时应用已打开，请运行 /usr/bin/open --env CODEX_APP_SERVER_USE_LOCAL_DAEMON=1 -a ChatGPT 重新启动应用。不要重发排队邮件。",
  "guidance.connectorOffline.title": "提供方连接器离线",
  "guidance.connectorOffline.body": "Embassy 当前无法访问本地提供方连接器。",
  "guidance.connectorOffline.action":
    "运行 embassy status。如果必须重启代理，排队邮件会保留并精确恢复一次；只有崩溃时正在写入的投递会以结果不确定结算。",
  "guidance.routeStale.title": "路由需要重新观察",
  "guidance.routeStale.body": "该路由不再具有当前端点证明。",
  "guidance.routeStale.action": "刷新并恢复相应选择或注册。",
  "guidance.queueStalled.title": "排队投递停滞",
  "guidance.queueStalled.body": "最早接受的消息已排队超过投递截止时间的一半。",
  "guidance.queueStalled.action":
    "运行 embassy status。不要重发已接受的工作；Embassy 会跟踪到结算或过期。",
  "guidance.queueStalled.busy":
    "该 Codex 方向队列只有在接收方当前轮次结束后才会到达。如果您控制该接收方，请结束该轮次。",
  "guidance.recipientWaitingInput.title": "消息已写入邮箱，但接收方仍未被观察到",
  "guidance.recipientWaitingInput.body":
    "Embassy 已将消息写入接收方消息邮箱，且当前未观察到接收方会话。",
  "guidance.recipientWaitingInput.action":
    "请在接收方会话自己的窗口中查看；不要重发已接受的消息。",
  "guidance.unconfirmed.title": "无法确认投递",
  "guidance.unconfirmed.body":
    "本地传输写入已完成，但该次尝试结算时没有可用的终结原生证据。",
  "guidance.unconfirmed.action": "重试前检查接收方；重试可能造成重复消息。",
  "guidance.degraded.title": "交换状态降级",
  "guidance.degraded.body": "Embassy 保留了一条规范化的连接器警告。",
  "guidance.degraded.action":
    "运行 embassy status。如果必须重启代理，排队邮件会保留并精确恢复一次；只有崩溃时正在写入的投递会以结果不确定结算。",
  "guidance.generic.title": "Embassy 报告了规范化警告",
  "guidance.generic.body": "面板没有为此安全代码映射自动修复方案。",
  "guidance.generic.action": "检查 embassy status。绝不要自动重试结果不确定的投递。",
  "guidance.codexSuccessionBusy.title": "更换 Codex 任务需要等待静默边界",
  "guidance.codexSuccessionBusy.body":
    "由于已接受或正在进行的工作尚未完全排空，Embassy 保留了当前 Codex 注册。",
  "guidance.codexSuccessionBusy.action":
    "等待当前工作进入终结状态，运行 embassy status，然后重试同一条 register-codex --alias <new> --succeeds <old> 命令。",
  "guidance.codexSuccessionRecovery.title": "更换 Codex 任务需要手动恢复",
  "guidance.codexSuccessionRecovery.body":
    "任务更换未能到达安全的活跃代次。Embassy 会让 Codex 注册保持离线，而不会猜测哪个任务拥有路由。",
  "guidance.codexSuccessionRecovery.action":
    "请勿发送消息、重试任务更换或假定任一任务处于活跃状态。运行 embassy status，并保留当前状态以供手动恢复。",
  "guidance.progressWatch.title": "受监视的对话已安静",
  "guidance.progressWatch.body":
    "Embassy 正在监视这项以完成为终止条件的对话，并且已发送至少一次空闲提醒。",
  "guidance.progressWatch.action":
    "请检查工作方路由和最近的监视历史。任一参与方都可用精确的 DONE: 结束监视；操作员也可运行 embassy untrack --conversation <token>。",
  "guidance.registryEmpty.title": "Claude 注册表尚未提供可解析记录",
  "guidance.registryEmpty.body":
    "自本次代理启动以来，尚未观察到必需字段可解析的 Claude 注册表记录。如果 Claude 正在运行，其注册表布局可能已经改变。",
  "guidance.registryEmpty.action":
    "运行 embassy refresh-dashboard。如果 Claude 正在运行且此状态仍存在，请在 embassy status 中查看“注册表观察”。",
  "guidance.registryRejected.title": "Claude 注册表扫描报告了问题",
  "guidance.registryRejected.body":
    "最近一次有界扫描无法读取注册表，或拒绝了一条或多条记录。其他记录（如有）将继续接受正常验证。",
  "guidance.registryRejected.action":
    "运行 embassy status，并查看“注册表观察”中的各安全代码计数。",
  "transit.eyebrow": "传输中",
  "transit.title": "队列状态",
  "transit.queued": "排队消息",
  "transit.active": "活跃投递",
  "transit.oldest": "最长排队时间",
  "transit.empty": "快照时没有排队消息。",
  "transit.unavailable": "时间戳不可用",
  "count.atLeast": "至少 {count}",
  "watches.eyebrow": "进度监视",
  "watches.title": "活跃进度监视",
  "watches.note":
    "任一参与方报告精确的 DONE: 都会结束监视；不显示消息正文或完整对话令牌。",
  "watches.empty": "当前没有受监视的对话。",
  "watches.column.conversation": "对话",
  "watches.column.parties": "所有者 → 工作方",
  "watches.column.quietFor": "安静时长",
  "watches.column.nextAction": "下次检查",
  "watches.column.nudges": "提醒次数",
  "watches.history.title": "最近监视历史",
  "watches.event.opened": "由 TRACK: 开启",
  "watches.event.replaced": "由较新的 TRACK: 替代",
  "watches.event.settled": "已终结",
  "watches.actor.owner": "所有者",
  "watches.actor.worker": "工作方",
  "watches.actor.operator": "操作员",
  "watches.actor.gateway": "Embassy",
  "watches.actor.unknown": "未知行为方",
  "watches.reason.done": "精确的 DONE:",
  "watches.reason.untracked": "操作员取消监视",
  "watches.reason.idleTimeout": "达到空闲上限",
  "watches.reason.pairRemoved": "同意边已移除",
  "watches.reason.endpointRetired": "端点已退役",
  "watches.reason.trackingDisabled": "监视已禁用",
  "activity.eyebrow": "活动记录",
  "activity.title": "最近投递证据",
  "activity.note": "绝不包含正文或提供方内部数据。",
  "activity.empty": "尚未记录投递元数据。",
  "activity.column.updated": "更新时间",
  "activity.column.route": "路由",
  "activity.column.id": "编号",
  "activity.column.result": "结果",
  "activity.column.elapsed": "耗时",
  "activity.column.size": "大小",
  "activity.column.history": "证据",
  "activity.history.one": "1 个阶段",
  "activity.history.many": "{count} 个阶段",
  "activity.meaning.delivered":
    "已达到 delivered 终局状态。这不表示模型已经读取或处理该消息。",
  "activity.meaning.delivered.toClaude":
    "Embassy 已立即将消息写入 Claude 的原生消息邮箱，并未等待路由空闲。这不表示模型已经读取或处理该消息。",
  "activity.meaning.delivered.toCodex":
    "Codex App Server 已接受该轮输入。这不表示模型已经完成或处理该输入。",
  "activity.meaning.delivered.toDeepSeek":
    "DeepSeek 已接受该投递。这不表示模型已经完成或处理该输入。",
  "activity.meaning.delivered.toGrok":
    "Grok Build 已接受该投递。这不表示模型已经完成或处理该输入。",
  "activity.meaning.unconfirmed":
    "传输写入已完成，但终结原生证据不可用。重试前请检查接收方。",
  "activity.meaning.ambiguous": "不确定写入后的结果未知。请勿自动重试。",
  "activity.meaning.other": "这是最新的规范化投递状态。",
  "activity.meaning.queued": "正在本地等待提供方写入；仅 Claude 忙碌状态不会导致排队。是进行中，不代表成功。",
  "activity.meaning.dispatching":
    "正在移交给接收端连接器。是进行中，不代表成功。",
  "activity.meaning.transportWritten":
    "已写入接收方传输通道，最终回执尚未到达。是进行中，不代表成功。",
  "activity.meaning.held": "写入已完成；接收方在其审批闸门后暂挂处理。",
  "activity.meaning.duplicate": "与已接收消息重复。本条从未被接收。",
  "activity.meaning.rejected":
    "在接收前被拒绝——例如截止时间无效或队列已满。它从未进入队列。",
  "activity.meaning.senderNotPaired":
    "当前配对策略拒绝了此发送方；消息正文未被接受。",
  "activity.meaning.failed":
    "已按失败终局。安全代码说明原因；切勿自动重试结果不确定的投递。",
  "activity.meaning.expired": "在观察到任何传输写入之前，投递截止时间已过。",
  "activity.meaning.cancelled": "在终局前被明确取消。",
  "activity.meaning.abandoned.controllerRestarted":
    "broker 在终局前停止——属设计行为；重启之间不转移任何内容。",
  "activity.meaning.abandoned.transientBody":
    "内存中的消息正文在派发前已不可用。",
  "activity.meaning.abandoned.routeTerminated": "其路由在投递终局前被注销。",
  "activity.meaning.abandoned.generic": "在完成前按放弃终局；详见安全代码。",
  "direction.claudeToCodex": "Claude → Codex",
  "direction.codexToClaude": "Codex → Claude",
  "delivery.queued": "已排队",
  "delivery.duplicate": "重复",
  "delivery.dispatching": "正在投递",
  "delivery.transportWritten": "已写入传输层",
  "delivery.held": "已暂存",
  "delivery.delivered": "已投递",
  "delivery.unconfirmed": "未确认",
  "delivery.failed": "失败",
  "delivery.ambiguous": "结果不确定",
  "delivery.expired": "已超出投递期限",
  "delivery.cancelled": "已取消",
  "delivery.abandoned": "已放弃",
  "delivery.rejected": "已拒绝",
  "sessions.eyebrow": "会话与路由",
  "sessions.title": "登记簿",
  "sessions.note": "仅显示公开别名；原生标识符已省略。",
  "sessions.peers.title": "已发现的 Claude 会话",
  "sessions.peers.empty": "此快照中没有可见的 Claude 会话。",
  "sessions.peers.caption": "已发现的 Claude 会话及选择状态",
  "sessions.routes.title": "消息路由",
  "sessions.routes.empty": "尚未注册或选择路由。",
  "sessions.routes.caption": "已注册及已选择的消息路由",
  "column.alias": "别名",
  "column.host": "主机",
  "column.provider": "提供方",
  "column.state": "状态",
  "column.selection": "选择",
  "column.validation": "验证",
  "status.validated": "已验证",
  "status.validationRejected": "已拒绝",
  "column.queue": "队列",
  "column.observed": "观察时间",
  "column.issue": "问题",
  "diagnostics.title": "系统详情",
  "diagnostics.note": "固定协议、计数器与有界显示说明",
  "diagnostics.connectors": "连接器",
  "diagnostics.connectors.empty": "没有连接器元数据。",
  "diagnostics.connectors.caption": "本地提供方连接器状态",
  "diagnostics.registry.title": "注册表观察",
  "diagnostics.registry.entriesScanned": "已扫描条目",
  "diagnostics.registry.parseableRecords": "必需字段可解析的记录",
  "diagnostics.registry.rejected": "按安全代码统计的已拒绝记录",
  "diagnostics.registry.rejectedNone": "无",
  "diagnostics.registry.rejectedCodesOmitted": "另有 {count} 个拒绝代码被省略",
  "diagnostics.registry.state.parseableRecordObserved": "已观察到可解析的必需字段",
  "diagnostics.registry.state.emptySinceBoot": "自代理启动以来为空",
  "diagnostics.registry.state.noParseableRecordSinceBoot":
    "自代理启动以来没有可解析记录",
  "diagnostics.protocol": "协议",
  "diagnostics.health": "健康状态",
  "diagnostics.accounting": "计数快照",
  "diagnostics.accepted": "已接受",
  "diagnostics.duplicates": "重复项",
  "diagnostics.delivered": "已投递",
  "diagnostics.unconfirmed": "未确认",
  "diagnostics.ambiguous": "结果不确定",
  "diagnostics.failed": "失败",
  "diagnostics.expired": "超出投递期限",
  "diagnostics.cancelled": "已取消",
  "diagnostics.abandoned": "已放弃",
  "diagnostics.rejected": "已拒绝",
  "diagnostics.bytesAccepted": "已接受字节",
  "diagnostics.queuedBytes": "排队字节",
  "diagnostics.omissions": "有界显示",
  "diagnostics.omissions.none": "没有省略内容。",
  "diagnostics.omissions.connectors": "{count} 个连接器",
  "diagnostics.omissions.peers": "{count} 个会话",
  "diagnostics.omissions.routes": "{count} 条路由",
  "diagnostics.omissions.consentEdges": "{count} 条同意边",
  "diagnostics.omissions.progressWatches": "{count} 项进度监视",
  "diagnostics.omissions.upstreamProgressWatchEvents":
    "面板投影前的 {count} 条监视事件",
  "diagnostics.omissions.progressWatchEvents": "{count} 条监视历史",
  "diagnostics.omissions.upstreamMessageEvents":
    "面板投影前的 {count} 条投递事件",
  "diagnostics.omissions.messageGroups": "{count} 组投递",
  "diagnostics.omissions.messageEvents": "{count} 条证据记录",
  "diagnostics.omissions.upstreamAlerts": "面板投影前的 {count} 个警告",
  "diagnostics.omissions.attentionItems": "{count} 个待处理项",
  "diagnostics.omissions.upstreamActivityEvents":
    "面板投影前的 {count} 条操作者操作记录",
  "diagnostics.omissions.activityEvents": "{count} 条操作者操作记录",
  "provider.claude": "Claude",
  "provider.codex": "Codex",
  "provider.deepseek": "DeepSeek",
  "provider.grok": "Grok Build",
  "health.offline": "离线",
  "health.connecting": "连接中",
  "health.healthy": "健康",
  "health.degraded": "降级",
  "health.meaning.healthy": "已连接并在交换心跳。",
  "health.meaning.connecting": "正在建立本地连接。",
  "health.meaning.degraded": "已连接，但保留了警告。",
  "health.meaning.offline": "在本机上无法访问。",
  "route.stale": "已过时",
  "route.idle": "空闲",
  "route.busy": "忙碌",
  "route.awaitingApproval": "等待批准",
  "route.offline": "离线",
  "route.disabled": "已停用",
  "route.meaning.idle": "已启用，可以承载消息。",
  "route.meaning.busy": "发往 Claude 的消息仍会立即写入原生消息邮箱；发往 Codex 的普通消息会等待路由空闲。",
  "route.meaning.awaitingApproval": "正在等待提供方的原生审批。",
  "route.meaning.stale": "当前没有端点证明；请刷新并恢复该路由。",
  "route.meaning.offline": "该路由的连接器无法访问。",
  "route.meaning.disabled": "已被管理性停用，不属于故障。",
  "peer.idle": "空闲",
  "peer.busy": "忙碌",
  "peer.awaitingApproval": "等待批准",
  "peer.offline": "离线",
  "peer.meaning.idle": "在线且可选择。",
  "peer.meaning.busy": "在线，但正处于一轮对话中。",
  "peer.meaning.awaitingApproval": "正在等待原生审批。",
  "peer.meaning.offline": "此前已发现，当前不在线——是候选项，不是错误。",
  "peer.reason.aliasCollision": "别名冲突：请重命名其中一个 Claude 会话，然后刷新发现。",
  "peer.reason.sessionCollision":
    "会话标识冲突：请关闭重复的会话记录，然后刷新发现。",
  "peer.reason.discoveryIncomplete":
    "发现结果不完整。请等待 Claude Code 完成会话清单发布后再刷新。",
  "peer.reason.offline": "此会话当前不在线。",
  "time.atSnapshot": "快照时",
  "time.beforeSnapshot": "快照前 {age}",
  "time.afterSnapshot": "快照后 {age}",
  "time.unavailable": "—",
  "time.ago": "{duration}前",
  "live.title": "Embassy — 实时面板",
  "live.noscript":
    "此实时视图需要 JavaScript。状态目录中的静态 gateway-dashboard.html 仍为离线底线。",
  "live.label": "实时伴侣",
  "live.mastheadSubtitle": "实时元数据流，并提供有限的路由同意控制。serve 仍限套接字通道。",
  "live.readonlyFooter":
    "此视图仅可配对、取消配对、刷新 Claude 发现结果，以及请求移除陈旧的 Codex 注册。",
  "live.action.authorityLabel": "有限的操作权限",
  "live.action.authorityBody":
    "此视图可配对或取消配对具名端点、刷新 Claude 发现结果，并且仅在代理确认具名 Codex 注册陈旧且其端点代际已失效时请求移除；不能注册任务、发送、回复、批准、中断或更改设置。",
  "live.action.sectionTitle": "有限的路由操作",
  "live.action.scope":
    "可为具名 Claude 与 Codex 端点配对或取消配对、刷新发现结果，或回收孤立的 Codex 别名。每项操作都必须确认并由代理重新验证。",
  "live.action.pair": "配对端点",
  "live.action.unpair": "取消端点配对",
  "live.action.removeStaleCodexRegistration": "移除陈旧注册",
  "live.action.refresh": "刷新发现结果",
  "live.action.confirm": "确认",
  "live.action.cancel": "取消",
  "live.action.pending": "处理中…",
  "live.action.succeeded": "已完成 · {code}",
  "live.action.failed": "未完成 · {code}",
  "live.action.requiresConnected": "请先重新连接并获取当前代理状态，再执行此操作。",
  "live.connection.connecting": "正在连接…",
  "live.connection.connected": "数据流已连接",
  "live.connection.unavailable": "观察器不可用 — 正在重试",
  "live.connection.capacity":
    "已打开 4 个实时面板窗口——请关闭一个，然后重新连接",
  "live.connection.disconnected": "连接已断开 — 请点击“重新连接”",
  "live.connection.fatal": "面板会话不可用",
  "live.connection.paused": "更新已暂停",
  "live.connection.stopped": "面板已停止",
  "live.control.pause": "暂停",
  "live.control.reconnect": "重新连接",
  "live.control.refresh": "立即读取",
  "live.filter.placeholder": "筛选别名与活动",
  "live.metric.queued": "排队中",
  "live.metric.active": "活跃",
  "live.attention.empty": "当前没有需要处理的项目。",
  "live.activity.empty": "尚无投递元数据。",
  "live.sessions.title": "会话",
  "live.diagnostics.title": "诊断",
  "live.metric.revision": "流版本",
  "live.stream.reset": "来源已重启；视图已重新同步。",
  "live.http.badRequest": "请求无效。",
  "live.http.forbidden": "禁止访问。",
  "live.http.notFound": "未找到。",
  "live.http.methodNotAllowed": "不允许使用此方法。",
  "live.http.bodyTooLarge": "请求正文过大。",
  "live.http.targetTooLarge": "请求目标过长。",
  "live.http.unsupportedMediaType": "不支持此媒体类型。",
  "live.http.tooManyStreams":
    "已打开 4 个实时面板窗口。请关闭一个，然后重新连接。",
  "live.http.headersTooLarge": "请求头过大。",
  "live.http.snapshotUnavailable": "面板快照不可用。",
  "live.http.requestFailed": "请求失败。",
  "live.http.starting": "面板正在启动。",
  "app.tab.overview": "总览",
  "app.tab.deliveries": "投递",
  "app.tab.routes": "路由与会话",
  "app.tab.activity": "活动",
  "app.tab.diagnostics": "诊断",
  "app.search.label": "搜索别名、消息后缀与安全代码",
  "app.search.placeholder": "搜索 — 回车打开“投递”",
  "app.asOf": "截至 {time}",
  "app.stale": "已有 {age} 未收到新帧，页面所示可能已不是当前状态。",
  "app.missedFrames": "有数据帧丢失。视图已按当前快照重新读取。",
  "app.lowerBound": "至少 {count}；显示数量有上限。",
  "app.copy": "复制",
  "app.copied": "已复制",
  "app.copyFailed": "复制失败——请手动选择文本",
  "app.staleQuiet": "连接正常；已有 {age} 无任何变化。",
  "app.notLanded.title": "此版本尚未提供",
  "app.notLanded.body":
    "实时契约还没有承载这项内容，因此这里没有可点击的控件。请改用下面的命令。",
  "app.show": "展开",
  "app.hide": "收起",
  "app.overview.statusStrip": "系统状态",
  "app.overview.broker": "Broker",
  "app.overview.claudeConn": "Claude 连接器",
  "app.overview.codexConn": "Codex 连接器",
  "app.overview.connectorMissing": "未报告连接器",
  "app.overview.node.claude.title": "claude",
  "app.overview.node.claude.sub": "会话",
  "app.overview.node.codex.title": "codex",
  "app.overview.node.codex.sub": "任务",
  "app.overview.count.codex":
    "已就绪 {ready} · 已注册 {total}",
  "app.overview.noPair.title": "没有同意边",
  "app.overview.noPair.body":
    "配对入站仅接受由显式同意边连接到已注册 Codex 任务的发送方；Codex 也只沿显式边路由。",
  "app.overview.degradedEdge": "有一条已显示的同意边尚未就绪。",
  "app.overview.degradedEdges": "部分同意边仍然保留，但尚未就绪。",
  "app.overview.queueC2x": "Claude → Codex",
  "app.overview.queueX2c": "Claude ← Codex",
  "app.overview.depth": "深度",
  "app.overview.oldest": "最长等待",
  "app.overview.pulse.title": "活动脉冲 — 终局状态，最近一小时",
  "app.overview.pulse.caption": "仅统计已保留的投递分组；更早的证据已被丢弃。",
  "app.overview.pulse.empty": "最近一小时没有投递达成终局。",
  "app.overview.viewIn": "在“投递”中查看",
  "app.deliveries.title": "投递",
  "app.deliveries.caption": "已保留的投递分组，最新在前",
  "app.deliveries.dir.label": "方向",
  "app.deliveries.dir.all": "全部",
  "app.deliveries.dir.codexToClaude": "Claude ← Codex",
  "app.deliveries.fromProvider": "发送提供方",
  "app.deliveries.toProvider": "接收提供方",
  "app.deliveries.providerAll": "所有提供方",
  "app.deliveries.view.label": "视图",
  "app.deliveries.view.byRoute": "按路由对",
  "app.deliveries.view.flat": "平铺列表",
  "app.deliveries.state.all": "全部",
  "app.deliveries.search": "搜索后缀、别名或安全代码",
  "app.deliveries.noMatch": "没有符合此筛选条件的投递。可用以下命令发送一条",
  "app.deliveries.pickRow": "选择一条投递以追踪其生命周期。",
  "app.deliveries.lifecycle": "生命周期",
  "app.deliveries.frames": "诊断帧",
  "app.deliveries.noFrames": "此投递没有记录任何安全代码。",
  "app.deliveries.raw": "原始 JSON",
  "app.deliveries.hideRaw": "隐藏原始 JSON",
  "app.deliveries.bodyLabel": "消息正文",
  "app.deliveries.bodiesNote": "此条投递没有保留正文。",
  "app.deliveries.noConv":
    "实时契约不携带会话标识，因此投递按路由对分组，而不是按会话线索分组。",
  "app.deliveries.eventsTruncated": "有 {count} 条较早的状态变化因保留额度被丢弃。",
  "app.deliveries.earliestRetained": "最早保留的事件",
  "app.routes.topology": "同意拓扑",
  "app.routes.candidates": "候选项",
  "app.routes.claudeSessions": "Claude 会话",
  "app.routes.codexRoutes": "Codex 任务",
  "app.routes.pairs": "同意边",
  "app.routes.pairDescription": "同意边：{claude} ↔ {codex}",
  "app.routes.unpairedProvider": "{provider}：{count} 个就绪端点尚无同意边",
  "app.routes.consentEndpoint": "{provider} · {alias}",
  "app.routes.consentEdge": "{left} ↔ {right}",
  "app.routes.pairState.degraded": "已降级",
  "app.routes.pairState.unavailable": "不可用",
  "app.routes.pairDegradedReason": "同意边仍然保留；一端或两端路由需要处理。",
  "app.routes.pairUnavailableReason":
    "同意边仍然保留；此快照中缺少一端或两端已保存路由的记录。",
  "app.routes.pairSummary": "就绪：{ready} · 同意边：{total}",
  "app.routes.unpairedSummary":
    "{claude} 个就绪 Claude 端点与 {codex} 个就绪 Codex 端点没有同意边。",
  "app.routes.pairCmd.consequence":
    "仅在 {claude} 与 {codex} 之间建立同意；现有边保持不变。",
  "app.routes.unpairCmd.consequence":
    "仅移除 {claude} 与 {codex} 之间的同意；相邻边上的工作保持活动。",
  "app.routes.selectCmd.title": "建立同意边",
  "app.routes.selectCmd.consequence":
    "在此 Claude 会话与一个 Codex 任务之间建立一条同意边；其他边保持不变。",
  "app.routes.selectCmd.consequenceOpen":
    "建立一条出站目标边。开放入站仍会接受同一操作系统用户下的任何在线 Claude 会话。",
  "app.routes.unselectCmd.consequence":
    "仅移除此同意边；相邻边上的工作保持活动。",
  "app.routes.unselectCmd.consequenceOpen":
    "仅移除此出站边。开放入站仍对同一操作系统用户下的所有在线 Claude 会话启用。",
  "app.routes.refreshCmd": "重新读取本地发现结果，并重写静态面板文件。",
  "app.routes.removeStaleCodex.consequence":
    "仅当代理确认 {alias} 的注册已陈旧且其端点代际已失效时才会移除。相关同意边也会移除；在线注册绝不会被触碰。",
  "app.routes.noPeers": "此快照中没有发现任何 Claude 会话。",
  "app.routes.noCodex": "尚未注册任何 Codex 任务。",
  "app.routes.successions": "继任历史",
  "app.routes.successions.empty": "当前没有正在进行的任务更换。",
  "app.routes.successions.note":
    "任务更换只是把别名移交给新的 Codex 任务。不转移任何内容：排队的工作、历史与审批都留在旧任务上。",
  "app.routes.detail.absent": "实时契约不携带此信息。",
  "app.routes.expandDetails": "展开 {alias} 的详情",
  "app.routes.collapseDetails": "收起 {alias} 的详情",
  "app.routes.queueDepth": "队列深度",
  "app.routes.counters": "路由计数器",
  "app.routes.registered": "已注册",
  "app.routes.registerHint":
    "注册不是按钮：它必须在 Codex 任务内运行以继承其身份。请让你的代理运行：",
  "app.routes.noPairInline":
    "无同意边 — 请将 Claude 会话与 Codex 任务配对",
  "app.omitted.pairs": "另有 {count} 条同意边未显示。",
  "app.activity.title": "事件流 — 有界，最新在前",
  "app.activity.kinds.all": "所有类型",
  "app.activity.kinds.delivery": "投递",
  "app.activity.kinds.operation": "操作者操作",
  "app.activity.kinds.alert": "警告",
  "app.activity.operation.discoveryRefreshed": "已刷新发现结果",
  "app.activity.operation.claudeSelected": "已选择 Claude 会话",
  "app.activity.operation.claudeUnselected": "已取消选择 Claude 会话",
  "app.activity.operation.codexRegistered": "已注册 Codex 任务",
  "app.activity.operation.codexSucceeded": "Codex 注册接续已完成",
  "app.activity.operation.codexUnregistered": "已注销 Codex 任务",
  "app.activity.operation.routesPaired": "已建立同意边",
  "app.activity.operation.routesUnpaired": "已移除同意边",
  "app.activity.operation.watchEnded": "已结束进度监视",
  "app.activity.operation.endpointRefreshed": "已刷新 Codex 端点",
  "app.activity.operation.codexOrphanRemoved": "已移除陈旧的 Codex 注册",
  "app.activity.operation.operator": "操作者",
  "app.activity.operation.automatic": "自动",
  "app.activity.operation.accepted": "已接受",
  "app.activity.operation.rejected": "已拒绝",
  "app.activity.limited":
    "操作者操作台账仅保留于本次代理进程。操作者操作行不携带消息正文；“投递”按设计显示已保留正文。完整能力令牌始终不会显示。",
  "app.activity.empty":
    "此窗口内没有内容。事件会随 broker 产生而出现；可以试试",
  "app.diag.versions": "连接器协议",
  "app.diag.versions.caption": "本地连接器已观察到的协议状态",
  "app.diag.col.provider": "提供方",
  "app.diag.col.host": "主机",
  "app.diag.col.protocol": "协议",
  "app.diag.col.version": "版本",
  "app.diag.versions.rangeAbsent":
    "连接器行显示已观察到的协议标记与当前健康状态。",
  "app.diag.lease.title": "租约 / 实例",
  "app.diag.lease.absent": "实时契约不携带租约状态。请用下面的命令查看本地状态。",
  "app.diag.limits": "限制与压力",
  "app.diag.limits.hint":
    "实时契约不公开当前配置值。请设置该环境变量，然后重新启动 embassy serve。",
  "app.diag.deadline.title": "投递截止时间",
  "app.diag.deadline.body":
    "自本次 broker 启动以来，已有 {count} 条投递超出截止时间。",
  "app.diag.deadline.retained":
    "保留证据：{terminal} 次终局尝试，其中 {expired} 次过期；当前截止时间为 {deadline}。",
  "app.diag.deadline.bucket.under1m": "少于 1 分钟",
  "app.diag.deadline.bucket.1to5m": "1–5 分钟",
  "app.diag.deadline.bucket.5to15m": "5–15 分钟",
  "app.diag.deadline.bucket.15to60m": "15–60 分钟",
  "app.diag.deadline.bucket.over60m": "超过 60 分钟",
  "app.diag.queue.title": "队列深度",
  "app.diag.queue.body": "当前有 {count} 条消息在排队。",
  "app.diag.bytes.title": "消息字节预算",
  "app.diag.bytes.body":
    "当前排队 {queued}；自本次 broker 启动以来共接受 {accepted}。",
  "app.diag.steering.title": "转向（steering）",
  "app.diag.steering.absent":
    "STEER 标记表示已分类的 Claude→Codex 投递证据。此元数据契约不公开操作员停用开关的当前设置。",
  "app.diag.deliveryNotices.title": "投递通知",
  "app.diag.deliveryNotices.note":
    "可设为 merged（默认）、verbose 或 quiet；更改后请重新启动 embassy serve。",
  "app.diag.editable.title": "设置",
  "app.diag.editable.note":
    "设置在 embassy serve 启动时从环境变量读取。此页面无法修改它们，因此不会把它们显示为可编辑控件。",
  "app.diag.counters": "计数器",
  "app.diag.counters.caption": "本次 broker 进程的累计计数器",
  "app.diag.omissions": "有界显示",
  "app.diag.omissions.caption": "按类别统计的显示前省略行数",
  footer: "只读元数据快照。无脚本、修改控件、外部资源、遥测或网络请求。",
} satisfies DashboardCopy;
