import type { DashboardCopy } from "./dashboard-copy.js";

export const dashboardCopyEn = {
  "meta.title": "Embassy — local exchange register",
  skip: "Skip to Embassy status",
  "language.label": "Language",
  "language.en": "English",
  "language.zhCn": "简体中文",
  "brand.eyebrow": "Local agent exchange",
  "brand.title": "Embassy",
  "brand.subtitle":
    "A point-in-time, metadata-only register of routes between Claude Code and Codex.",
  "snapshot.asOf": "Snapshot {time}",
  "snapshot.static":
    "This file does not update itself. Reload it to read the latest published snapshot.",
  "overall.ready": "Exchange ready",
  "overall.setup": "Setup incomplete",
  "overall.attention": "Needs attention",
  "exchange.eyebrow": "Exchange board",
  "exchange.title": "Two directions, two explicit boundaries",
  "exchange.note":
    "Codex sends only to a selected Claude session. Every compatible live Claude session under the same OS user can see a registered Codex task.",
  "exchange.claude.title": "Claude selection",
  "exchange.claude.note": "Destination for Codex → Claude",
  "exchange.codex.title": "Codex registration",
  "exchange.codex.note": "Target for Claude → Codex",
  "exchange.pouch.title": "Local pouch",
  "exchange.pouch.empty": "Queue clear",
  "exchange.pouch.queued": "{count} queued",
  "exchange.pouch.oldest": "Oldest wait {age}",
  "exchange.count.claude":
    "{ready} selected · {selectable} selectable · {total} discovered",
  "exchange.count.codex": "{ready} ready · {total} registered",
  "status.ready": "Ready",
  "status.busy": "Busy",
  "status.waiting": "Waiting",
  "status.missing": "Not configured",
  "status.attention": "Unavailable",
  "status.selected": "Selected",
  "status.available": "Available",
  "status.notSelectable": "Not selectable",
  "status.enabled": "Enabled",
  "status.disabled": "Disabled",
  "next.label": "Next",
  "next.none": "No action needed.",
  "next.discoverClaude":
    "Keep Claude Code running with crossSessionInbound enabled, then run embassy refresh-dashboard.",
  "next.selectClaude":
    "Run embassy select-claude --alias <alias> to choose a visible session explicitly.",
  "next.restoreClaude":
    "Refresh discovery, then explicitly select the current Claude alias if it is not restored.",
  "next.repairClaude":
    "No compatible, live, collision-free session is selectable. Resolve the issue shown in Sessions & routes, then refresh discovery.",
  "next.registerCodex":
    "Inside the Codex task, run embassy register-codex --alias codex-<name>@<host>.",
  "next.restoreCodex":
    "Re-run embassy register-codex --alias <alias> inside that exact Codex task.",
  "attention.eyebrow": "Needs attention",
  "attention.title": "Resolve before sending",
  "attention.count": "{count} active",
  "attention.countVisible": "{count} shown",
  "attention.projectionOnly":
    "Additional alert metadata was omitted before dashboard projection. Review the bounded-display note and run embassy status.",
  "attention.scope": "Scope",
  "severity.info": "Info",
  "severity.warning": "Warning",
  "severity.error": "Error",
  "guidance.reobserveClaude.title": "Claude selection needs observation",
  "guidance.reobserveClaude.body":
    "The saved route does not currently have a matching live endpoint proof.",
  "guidance.reobserveClaude.action":
    "Refresh discovery and explicitly select the current Claude alias.",
  "guidance.reobserveCodex.title": "Codex registration needs observation",
  "guidance.reobserveCodex.body":
    "The saved route does not currently have a matching live endpoint proof.",
  "guidance.reobserveCodex.action":
    "Re-run register-codex inside that exact Codex task.",
  "guidance.claudeNotObserved.title": "Selected Claude session is not visible",
  "guidance.claudeNotObserved.body":
    "The selected session is absent from current local discovery.",
  "guidance.claudeNotObserved.action":
    "Keep Claude running with crossSessionInbound enabled, refresh, then select its current alias.",
  "guidance.codexStale.title": "Codex route is stale",
  "guidance.codexStale.body":
    "The registered Codex task no longer has a ready App Server connection.",
  "guidance.codexStale.action":
    "Re-run register-codex with the same alias inside that exact Codex task. Do not unregister first.",
  "guidance.connectorOffline.title": "A provider connector is offline",
  "guidance.connectorOffline.body":
    "Embassy cannot currently reach the local provider connector.",
  "guidance.connectorOffline.action":
    "Run embassy status. Restart only when queued messages and active deliveries are both zero; restarting abandons memory-only message bodies.",
  "guidance.routeStale.title": "A route is stale",
  "guidance.routeStale.body": "The route no longer has current endpoint proof.",
  "guidance.routeStale.action":
    "Refresh and restore the matching selection or registration.",
  "guidance.queueStalled.title": "Queued delivery is stalled",
  "guidance.queueStalled.body":
    "The oldest accepted message remains queued past half of its delivery deadline.",
  "guidance.queueStalled.action":
    "Run embassy status. Do not resend accepted work; Embassy still tracks it until settlement or expiry.",
  "guidance.unconfirmed.title": "Delivery could not be confirmed",
  "guidance.unconfirmed.body":
    "The local transport write completed, but no terminal native receipt arrived before the deadline.",
  "guidance.unconfirmed.action":
    "Inspect the recipient before retrying; a retry could duplicate the message.",
  "guidance.degraded.title": "The exchange is degraded",
  "guidance.degraded.body":
    "Embassy retained a normalized compatibility or connector warning.",
  "guidance.degraded.action":
    "Run embassy status. Restart only when queued messages and active deliveries are both zero; restarting abandons memory-only message bodies.",
  "guidance.generic.title": "Embassy reported a normalized alert",
  "guidance.generic.body":
    "This safe code has no automatic repair mapped in the dashboard.",
  "guidance.generic.action":
    "Review embassy status. Never automatically retry an ambiguous delivery.",
  "transit.eyebrow": "In transit",
  "transit.title": "Queue posture",
  "transit.queued": "Queued messages",
  "transit.active": "Active deliveries",
  "transit.oldest": "Oldest queue age",
  "transit.empty": "No queued messages at snapshot time.",
  "transit.unavailable": "Timestamp unavailable",
  "count.atLeast": "At least {count}",
  "activity.eyebrow": "Activity ledger",
  "activity.title": "Recent delivery evidence",
  "activity.note": "Bodies and provider internals are never included.",
  "activity.empty": "No delivery metadata has been recorded yet.",
  "activity.column.updated": "Updated",
  "activity.column.route": "Route",
  "activity.column.id": "ID",
  "activity.column.result": "Result",
  "activity.column.elapsed": "Elapsed",
  "activity.column.size": "Size",
  "activity.column.history": "Evidence",
  "activity.history.one": "1 stage",
  "activity.history.many": "{count} stages",
  "activity.meaning.delivered":
    "Provider-specific terminal evidence was observed. A released Claude receipt means acceptance into the recipient queue, not that the model read or acted on the message.",
  "activity.meaning.unconfirmed":
    "The transport write completed, but terminal native evidence was unavailable. Inspect the recipient before retrying.",
  "activity.meaning.ambiguous":
    "The outcome is unknown after an uncertain write. Do not retry automatically.",
  "activity.meaning.other": "This is the latest normalized delivery state.",
  "direction.claudeToCodex": "Claude → Codex",
  "direction.codexToClaude": "Codex → Claude",
  "delivery.queued": "Queued",
  "delivery.duplicate": "Duplicate",
  "delivery.dispatching": "Dispatching",
  "delivery.transportWritten": "Transport written",
  "delivery.held": "Held",
  "delivery.delivered": "Delivered",
  "delivery.unconfirmed": "Unconfirmed",
  "delivery.failed": "Failed",
  "delivery.ambiguous": "Ambiguous",
  "delivery.expired": "Expired",
  "delivery.cancelled": "Cancelled",
  "delivery.abandoned": "Abandoned",
  "delivery.rejected": "Rejected",
  "sessions.eyebrow": "Sessions & routes",
  "sessions.title": "Accreditation register",
  "sessions.note": "Public aliases only; native identifiers are omitted.",
  "sessions.peers.title": "Discovered Claude sessions",
  "sessions.peers.empty": "No Claude sessions are visible in this snapshot.",
  "sessions.peers.caption": "Discovered Claude sessions and selection state",
  "sessions.routes.title": "Message routes",
  "sessions.routes.empty": "No routes are registered or selected.",
  "sessions.routes.caption": "Registered and selected message routes",
  "column.alias": "Alias",
  "column.host": "Host",
  "column.provider": "Provider",
  "column.state": "State",
  "column.compatibility": "Compatibility",
  "column.selection": "Selection",
  "column.queue": "Queue",
  "column.observed": "Observed",
  "column.issue": "Issue",
  "diagnostics.title": "Compatibility & system details",
  "diagnostics.note": "Pinned protocols, counters, and bounded-display notes",
  "diagnostics.connectors": "Connectors",
  "diagnostics.connectors.empty": "No connector metadata is available.",
  "diagnostics.connectors.caption": "Local provider connector status",
  "diagnostics.protocol": "Protocol",
  "diagnostics.health": "Health",
  "diagnostics.accounting": "Accounting snapshot",
  "diagnostics.accepted": "Accepted",
  "diagnostics.duplicates": "Duplicates",
  "diagnostics.delivered": "Delivered",
  "diagnostics.unconfirmed": "Unconfirmed",
  "diagnostics.ambiguous": "Ambiguous",
  "diagnostics.failed": "Failed",
  "diagnostics.expired": "Expired",
  "diagnostics.cancelled": "Cancelled",
  "diagnostics.abandoned": "Abandoned",
  "diagnostics.rejected": "Rejected",
  "diagnostics.bytesAccepted": "Bytes accepted",
  "diagnostics.queuedBytes": "Bytes queued",
  "diagnostics.omissions": "Bounded display",
  "diagnostics.omissions.none": "Nothing omitted.",
  "diagnostics.omissions.connectors": "{count} connectors",
  "diagnostics.omissions.peers": "{count} sessions",
  "diagnostics.omissions.routes": "{count} routes",
  "diagnostics.omissions.upstreamMessageEvents":
    "{count} delivery events before dashboard projection",
  "diagnostics.omissions.messageGroups": "{count} delivery groups",
  "diagnostics.omissions.messageEvents": "{count} evidence rows",
  "diagnostics.omissions.upstreamAlerts":
    "{count} alerts before dashboard projection",
  "diagnostics.omissions.attentionItems": "{count} attention items",
  "provider.claude": "Claude",
  "provider.codex": "Codex",
  "health.offline": "Offline",
  "health.connecting": "Connecting",
  "health.healthy": "Healthy",
  "health.degraded": "Degraded",
  "health.incompatible": "Incompatible",
  "compatibility.unknown": "Unknown",
  "compatibility.compatible": "Compatible",
  "compatibility.incompatible": "Incompatible",
  "compatibility.expired": "Expired",
  "route.stale": "Stale",
  "route.idle": "Idle",
  "route.busy": "Busy",
  "route.awaitingApproval": "Awaiting approval",
  "route.offline": "Offline",
  "route.incompatible": "Incompatible",
  "route.disabled": "Disabled",
  "peer.idle": "Idle",
  "peer.busy": "Busy",
  "peer.awaitingApproval": "Awaiting approval",
  "peer.offline": "Offline",
  "peer.incompatible": "Incompatible",
  "peer.reason.aliasCollision":
    "Alias collision: rename one Claude session, then refresh discovery.",
  "peer.reason.sessionCollision":
    "Session identity collision: close the duplicate session record, then refresh discovery.",
  "peer.reason.discoveryIncomplete":
    "Discovery was incomplete. Refresh after Claude Code finishes publishing its session inventory.",
  "peer.reason.incompatible":
    "This session is not compatible with the pinned Embassy protocol.",
  "peer.reason.offline": "This session is not currently live.",
  "time.atSnapshot": "At snapshot",
  "time.beforeSnapshot": "{age} before snapshot",
  "time.afterSnapshot": "{age} after snapshot",
  "time.unavailable": "—",
  footer:
    "Read-only metadata snapshot. No scripts, mutation controls, external assets, telemetry, or network requests.",
} satisfies DashboardCopy;
