import type { DashboardCopy } from "./dashboard-copy.js";

export const dashboardCopyZhCn = {
  "meta.title": "Embassy — 本地交换记录",
  skip: "跳至 Embassy 状态",
  "language.label": "语言",
  "language.en": "English",
  "language.zhCn": "简体中文",
  "brand.eyebrow": "本地智能体交换",
  "brand.title": "Embassy",
  "brand.subtitle": "Claude Code 与 Codex 路由在一个时间点的仅元数据记录。",
  "snapshot.asOf": "快照时间 {time}",
  "snapshot.static": "此文件不会自动更新。请重新载入以读取最新发布的快照。",
  "overall.ready": "交换已就绪",
  "overall.setup": "设置尚未完成",
  "overall.attention": "需要处理",
  "exchange.eyebrow": "交换台",
  "exchange.title": "两个方向，两道明确边界",
  "exchange.note":
    "Codex 只会向已选择的 Claude 会话发送消息。同一操作系统用户下，每个兼容且在线的 Claude 会话都能看到已注册的 Codex 任务。",
  "exchange.claude.title": "Claude 选择",
  "exchange.claude.note": "Codex → Claude 的目标",
  "exchange.codex.title": "Codex 注册",
  "exchange.codex.note": "Claude → Codex 的目标",
  "exchange.pouch.title": "本地信袋",
  "exchange.pouch.empty": "队列为空",
  "exchange.pouch.queued": "{count} 条排队中",
  "exchange.pouch.oldest": "最长等待 {age}",
  "exchange.count.claude":
    "已选择 {ready} · 可选择 {selectable} · 已发现 {total}",
  "exchange.count.codex": "已就绪 {ready} · 已注册 {total}",
  "status.ready": "就绪",
  "status.busy": "忙碌",
  "status.waiting": "等待中",
  "status.missing": "尚未配置",
  "status.attention": "不可用",
  "status.selected": "已选择",
  "status.available": "可用",
  "status.notSelectable": "不可选择",
  "status.enabled": "已启用",
  "status.disabled": "已停用",
  "next.label": "下一步",
  "next.none": "无需操作。",
  "next.discoverClaude":
    "保持 Claude Code 运行并启用 crossSessionInbound，然后运行 embassy refresh-dashboard。",
  "next.selectClaude":
    "运行 embassy select-claude --alias <alias>，明确选择一个可见会话。",
  "next.restoreClaude": "刷新发现；若未自动恢复，请明确选择 Claude 当前别名。",
  "next.repairClaude":
    "当前没有兼容、在线且无冲突的可选会话。请先解决“会话与路由”中显示的问题，再刷新发现。",
  "next.registerCodex":
    "在 Codex 任务内运行 embassy register-codex --alias codex-<name>@<host>。",
  "next.restoreCodex":
    "在该 Codex 任务内重新运行 embassy register-codex --alias <alias>。",
  "attention.eyebrow": "需要处理",
  "attention.title": "发送前请先解决",
  "attention.count": "{count} 项",
  "attention.countVisible": "显示 {count} 项",
  "attention.projectionOnly":
    "面板投影前省略了其他警告元数据。请查看有界显示说明并运行 embassy status。",
  "attention.scope": "范围",
  "severity.info": "信息",
  "severity.warning": "警告",
  "severity.error": "错误",
  "guidance.reobserveClaude.title": "需要重新观察 Claude 选择",
  "guidance.reobserveClaude.body": "已保存路由目前没有匹配的在线端点证明。",
  "guidance.reobserveClaude.action": "刷新发现并明确选择 Claude 当前别名。",
  "guidance.reobserveCodex.title": "需要重新观察 Codex 注册",
  "guidance.reobserveCodex.body": "已保存路由目前没有匹配的在线端点证明。",
  "guidance.reobserveCodex.action": "在该 Codex 任务内重新运行 register-codex。",
  "guidance.claudeNotObserved.title": "已选择的 Claude 会话不可见",
  "guidance.claudeNotObserved.body": "当前本地发现中没有该会话。",
  "guidance.claudeNotObserved.action":
    "保持 Claude 运行并启用 crossSessionInbound，刷新后选择其当前别名。",
  "guidance.codexStale.title": "Codex 路由需要重新观察",
  "guidance.codexStale.body": "已注册的 Codex 任务不再具有就绪的 App Server 连接。",
  "guidance.codexStale.action":
    "在该 Codex 任务内使用同一别名重新运行 register-codex；不要先注销。",
  "guidance.connectorOffline.title": "提供方连接器离线",
  "guidance.connectorOffline.body": "Embassy 当前无法访问本地提供方连接器。",
  "guidance.connectorOffline.action":
    "运行 embassy status。仅当排队消息和活跃投递均为零时才能重启；重启会放弃仅存于内存的消息正文。",
  "guidance.routeStale.title": "路由需要重新观察",
  "guidance.routeStale.body": "该路由不再具有当前端点证明。",
  "guidance.routeStale.action": "刷新并恢复相应选择或注册。",
  "guidance.queueStalled.title": "排队投递停滞",
  "guidance.queueStalled.body": "最早接受的消息已排队超过投递截止时间的一半。",
  "guidance.queueStalled.action":
    "运行 embassy status。不要重发已接受的工作；Embassy 会跟踪到结算或过期。",
  "guidance.unconfirmed.title": "无法确认投递",
  "guidance.unconfirmed.body": "本地传输写入已完成，但截止前未收到终结原生回执。",
  "guidance.unconfirmed.action": "重试前检查接收方；重试可能造成重复消息。",
  "guidance.degraded.title": "交换状态降级",
  "guidance.degraded.body": "Embassy 保留了一条规范化的兼容性或连接器警告。",
  "guidance.degraded.action":
    "运行 embassy status。仅当排队消息和活跃投递均为零时才能重启；重启会放弃仅存于内存的消息正文。",
  "guidance.generic.title": "Embassy 报告了规范化警告",
  "guidance.generic.body": "面板没有为此安全代码映射自动修复方案。",
  "guidance.generic.action": "检查 embassy status。绝不要自动重试结果不确定的投递。",
  "transit.eyebrow": "传输中",
  "transit.title": "队列状态",
  "transit.queued": "排队消息",
  "transit.active": "活跃投递",
  "transit.oldest": "最长排队时间",
  "transit.empty": "快照时没有排队消息。",
  "transit.unavailable": "时间戳不可用",
  "count.atLeast": "至少 {count}",
  "activity.eyebrow": "活动记录",
  "activity.title": "最近投递证据",
  "activity.note": "绝不包含正文或提供方内部数据。",
  "activity.empty": "尚未记录投递元数据。",
  "activity.column.updated": "更新时间",
  "activity.column.route": "路由",
  "activity.column.id": "编号",
  "activity.column.result": "结果",
  "activity.column.elapsed": "耗时",
  "activity.column.size": "大小",
  "activity.column.history": "证据",
  "activity.history.one": "1 个阶段",
  "activity.history.many": "{count} 个阶段",
  "activity.meaning.delivered":
    "已观察到提供方特定的终结证据。Claude 的 released 回执表示消息已进入接收方队列，不表示模型已经读取或处理该消息。",
  "activity.meaning.unconfirmed":
    "传输写入已完成，但终结原生证据不可用。重试前请检查接收方。",
  "activity.meaning.ambiguous": "不确定写入后的结果未知。请勿自动重试。",
  "activity.meaning.other": "这是最新的规范化投递状态。",
  "direction.claudeToCodex": "Claude → Codex",
  "direction.codexToClaude": "Codex → Claude",
  "delivery.queued": "已排队",
  "delivery.duplicate": "重复",
  "delivery.dispatching": "正在投递",
  "delivery.transportWritten": "已写入传输层",
  "delivery.held": "已暂存",
  "delivery.delivered": "已投递",
  "delivery.unconfirmed": "未确认",
  "delivery.failed": "失败",
  "delivery.ambiguous": "结果不确定",
  "delivery.expired": "已超出投递期限",
  "delivery.cancelled": "已取消",
  "delivery.abandoned": "已放弃",
  "delivery.rejected": "已拒绝",
  "sessions.eyebrow": "会话与路由",
  "sessions.title": "登记簿",
  "sessions.note": "仅显示公开别名；原生标识符已省略。",
  "sessions.peers.title": "已发现的 Claude 会话",
  "sessions.peers.empty": "此快照中没有可见的 Claude 会话。",
  "sessions.peers.caption": "已发现的 Claude 会话及选择状态",
  "sessions.routes.title": "消息路由",
  "sessions.routes.empty": "尚未注册或选择路由。",
  "sessions.routes.caption": "已注册及已选择的消息路由",
  "column.alias": "别名",
  "column.host": "主机",
  "column.provider": "提供方",
  "column.state": "状态",
  "column.compatibility": "兼容性",
  "column.selection": "选择",
  "column.queue": "队列",
  "column.observed": "观察时间",
  "column.issue": "问题",
  "diagnostics.title": "兼容性与系统详情",
  "diagnostics.note": "固定协议、计数器与有界显示说明",
  "diagnostics.connectors": "连接器",
  "diagnostics.connectors.empty": "没有连接器元数据。",
  "diagnostics.connectors.caption": "本地提供方连接器状态",
  "diagnostics.protocol": "协议",
  "diagnostics.health": "健康状态",
  "diagnostics.accounting": "计数快照",
  "diagnostics.accepted": "已接受",
  "diagnostics.duplicates": "重复项",
  "diagnostics.delivered": "已投递",
  "diagnostics.unconfirmed": "未确认",
  "diagnostics.ambiguous": "结果不确定",
  "diagnostics.failed": "失败",
  "diagnostics.expired": "超出投递期限",
  "diagnostics.cancelled": "已取消",
  "diagnostics.abandoned": "已放弃",
  "diagnostics.rejected": "未接受",
  "diagnostics.bytesAccepted": "已接受字节",
  "diagnostics.queuedBytes": "排队字节",
  "diagnostics.omissions": "有界显示",
  "diagnostics.omissions.none": "没有省略内容。",
  "diagnostics.omissions.connectors": "{count} 个连接器",
  "diagnostics.omissions.peers": "{count} 个会话",
  "diagnostics.omissions.routes": "{count} 条路由",
  "diagnostics.omissions.upstreamMessageEvents":
    "面板投影前的 {count} 条投递事件",
  "diagnostics.omissions.messageGroups": "{count} 组投递",
  "diagnostics.omissions.messageEvents": "{count} 条证据记录",
  "diagnostics.omissions.upstreamAlerts": "面板投影前的 {count} 个警告",
  "diagnostics.omissions.attentionItems": "{count} 个待处理项",
  "provider.claude": "Claude",
  "provider.codex": "Codex",
  "health.offline": "离线",
  "health.connecting": "连接中",
  "health.healthy": "健康",
  "health.degraded": "降级",
  "health.incompatible": "不兼容",
  "compatibility.unknown": "未知",
  "compatibility.compatible": "兼容",
  "compatibility.incompatible": "不兼容",
  "compatibility.expired": "兼容性观察已失效",
  "route.stale": "需要重新观察",
  "route.idle": "空闲",
  "route.busy": "忙碌",
  "route.awaitingApproval": "等待批准",
  "route.offline": "离线",
  "route.incompatible": "不兼容",
  "route.disabled": "已停用",
  "peer.idle": "空闲",
  "peer.busy": "忙碌",
  "peer.awaitingApproval": "等待批准",
  "peer.offline": "离线",
  "peer.incompatible": "不兼容",
  "peer.reason.aliasCollision": "别名冲突：请重命名其中一个 Claude 会话，然后刷新发现。",
  "peer.reason.sessionCollision":
    "会话标识冲突：请关闭重复的会话记录，然后刷新发现。",
  "peer.reason.discoveryIncomplete":
    "发现结果不完整。请等待 Claude Code 完成会话清单发布后再刷新。",
  "peer.reason.incompatible": "此会话与 Embassy 固定的协议版本不兼容。",
  "peer.reason.offline": "此会话当前不在线。",
  "time.atSnapshot": "快照时",
  "time.beforeSnapshot": "快照前 {age}",
  "time.afterSnapshot": "快照后 {age}",
  "time.unavailable": "—",
  footer: "只读元数据快照。无脚本、修改控件、外部资源、遥测或网络请求。",
} satisfies DashboardCopy;
