import type { GatewayPublicSnapshot } from "../src/gateway/types.js";

export function dashboardFixture(): GatewayPublicSnapshot {
  return {
    schemaVersion: 1,
    generatedAt: "2026-08-08T12:00:00.000Z",
    inboundMode: "paired",
    health: "healthy",
    connectors: [
      {
        provider: "claude",
        host: "this-mac",
        health: "healthy",
        compatibility: "compatible",
        protocol: "peer/1",
        protocolVersion: "1",
        lastSeenAt: "2026-08-08T11:59:58.000Z",
      },
      {
        provider: "codex",
        host: "this-mac",
        health: "healthy",
        compatibility: "compatible",
        protocol: "app-server/1",
        protocolVersion: "0.147.0",
        lastSeenAt: "2026-08-08T11:59:59.000Z",
      },
    ],
    availablePeers: [
      {
        alias: "claude-advisor@this-mac",
        provider: "claude",
        host: "this-mac",
        state: "busy",
        compatibility: "compatible",
        validated: true,
        selected: true,
        lastSeenAt: "2026-08-08T11:59:58.000Z",
      },
      {
        alias: "claude-reviewer@this-mac",
        provider: "claude",
        host: "this-mac",
        state: "idle",
        compatibility: "compatible",
        validated: true,
        selected: false,
        lastSeenAt: "2026-08-08T11:59:57.000Z",
      },
    ],
    routes: [
      {
        alias: "claude-advisor@this-mac",
        provider: "claude",
        host: "this-mac",
        enabled: true,
        state: "busy",
        compatibility: "compatible",
        busyPolicy: "queue",
        lastSeenAt: "2026-08-08T11:59:58.000Z",
        queueDepth: 0,
        counters: routeCounters({ accepted: 2, delivered: 1, unconfirmed: 1 }),
      },
      {
        alias: "codex-reviewer@this-mac",
        provider: "codex",
        host: "this-mac",
        enabled: true,
        state: "idle",
        compatibility: "compatible",
        busyPolicy: "queue",
        lastSeenAt: "2026-08-08T11:59:59.000Z",
        queueDepth: 2,
        oldestQueuedAt: "2026-08-08T11:58:29.500Z",
        counters: routeCounters({ accepted: 4, delivered: 3 }),
      },
    ],
    pairs: [
      {
        claudeAlias: "claude-advisor@this-mac",
        codexAlias: "codex-reviewer@this-mac",
        host: "this-mac",
        counters: routeCounters({ accepted: 4, delivered: 3 }),
      },
    ],
    activityEvents: [
      {
        sequence: 1,
        timestamp: "2026-08-08T11:59:54.000Z",
        kind: "pairing",
        action: "routes_paired",
        outcome: "accepted",
        aliases: [
          "claude-advisor@this-mac",
          "codex-reviewer@this-mac",
        ],
        operatorAction: true,
      },
    ],
    deadlinePressure: {
      configuredDeadlineMs: 300_000,
      retainedSince: "2026-08-08T11:59:55.000Z",
      terminalEvents: 3,
      expiredEvents: 0,
      buckets: [
        { bucket: "under_1m", settled: 3, expired: 0 },
        { bucket: "1m_to_5m", settled: 0, expired: 0 },
        { bucket: "5m_to_15m", settled: 0, expired: 0 },
        { bucket: "15m_to_60m", settled: 0, expired: 0 },
        { bucket: "over_60m", settled: 0, expired: 0 },
      ],
    },
    messages: [
      {
        sequence: 1,
        timestamp: "2026-08-08T11:59:55.000Z",
        messageIdSuffix: "a1b2c3",
        conversationIdSuffix: "AbCd_123",
        direction: "claude_to_codex",
        sourceAlias: "claude-advisor@this-mac",
        targetAlias: "codex-reviewer@this-mac",
        state: "queued",
        bytes: 128,
      },
      {
        sequence: 2,
        timestamp: "2026-08-08T11:59:57.000Z",
        messageIdSuffix: "a1b2c3",
        conversationIdSuffix: "AbCd_123",
        direction: "claude_to_codex",
        sourceAlias: "claude-advisor@this-mac",
        targetAlias: "codex-reviewer@this-mac",
        state: "delivered",
        latencyMs: 2_000,
        bytes: 128,
      },
      {
        sequence: 3,
        timestamp: "2026-08-08T11:59:58.000Z",
        messageIdSuffix: "c0ffee",
        conversationIdSuffix: "EfGh_456",
        direction: "codex_to_claude",
        sourceAlias: "codex-reviewer@this-mac",
        targetAlias: "claude-advisor@this-mac",
        state: "unconfirmed",
        latencyMs: 3_000,
        bytes: 96,
        safeErrorCode: "CLAUDE_RECEIPT_UNCONFIRMED",
      },
      {
        sequence: 4,
        timestamp: "2026-08-08T11:59:59.000Z",
        messageIdSuffix: "decaf0",
        conversationIdSuffix: "IjKl_789",
        direction: "codex_to_claude",
        sourceAlias: "codex-reviewer@this-mac",
        targetAlias: "claude-advisor@this-mac",
        state: "ambiguous",
        latencyMs: 4_000,
        bytes: 64,
        safeErrorCode: "CLAUDE_WRITE_AMBIGUOUS",
      },
    ],
    accounting: {
      accepted: 6,
      duplicates: 0,
      delivered: 4,
      unconfirmed: 1,
      failed: 0,
      ambiguous: 1,
      expired: 0,
      cancelled: 0,
      abandoned: 0,
      rejected: 0,
      bytesAccepted: 416,
      queuedBytes: 192,
    },
    alerts: [],
    truncation: {
      connectors: 0,
      availablePeers: 0,
      routes: 0,
      pairs: 0,
      activityEvents: 0,
      messages: 0,
      alerts: 0,
    },
  };
}

export function routeCounters(
  overrides: Partial<GatewayPublicSnapshot["routes"][number]["counters"]> = {},
): GatewayPublicSnapshot["routes"][number]["counters"] {
  return {
    accepted: 0,
    delivered: 0,
    unconfirmed: 0,
    failed: 0,
    ambiguous: 0,
    expired: 0,
    cancelled: 0,
    abandoned: 0,
    rejected: 0,
    bytesAccepted: 0,
    ...overrides,
  };
}
