import type { GatewayPublicSnapshot } from "../src/gateway/types.js";

export function dashboardFixture(): GatewayPublicSnapshot {
  return {
    schemaVersion: 1,
    generatedAt: "2026-08-08T12:00:00.000Z",
    health: "healthy",
    connectors: [
      {
        provider: "claude",
        host: "this-mac",
        health: "healthy",
        compatibility: "compatible",
        protocol: "peer/1",
        protocolVersion: "1",
        lastSeenAt: "2026-08-08T11:59:58.000Z",
      },
      {
        provider: "codex",
        host: "this-mac",
        health: "healthy",
        compatibility: "compatible",
        protocol: "app-server/1",
        protocolVersion: "0.147.0",
        lastSeenAt: "2026-08-08T11:59:59.000Z",
      },
    ],
    availablePeers: [
      {
        alias: "claude-advisor@this-mac",
        provider: "claude",
        host: "this-mac",
        state: "busy",
        compatibility: "compatible",
        selected: true,
        lastSeenAt: "2026-08-08T11:59:58.000Z",
      },
      {
        alias: "claude-reviewer@this-mac",
        provider: "claude",
        host: "this-mac",
        state: "idle",
        compatibility: "compatible",
        selected: false,
        lastSeenAt: "2026-08-08T11:59:57.000Z",
      },
    ],
    routes: [
      {
        alias: "claude-advisor@this-mac",
        provider: "claude",
        host: "this-mac",
        enabled: true,
        state: "busy",
        compatibility: "compatible",
        busyPolicy: "queue",
        lastSeenAt: "2026-08-08T11:59:58.000Z",
        queueDepth: 0,
        counters: routeCounters({ accepted: 2, delivered: 1, unconfirmed: 1 }),
      },
      {
        alias: "codex-reviewer@this-mac",
        provider: "codex",
        host: "this-mac",
        enabled: true,
        state: "idle",
        compatibility: "compatible",
        busyPolicy: "queue",
        lastSeenAt: "2026-08-08T11:59:59.000Z",
        queueDepth: 2,
        oldestQueuedAt: "2026-08-08T11:58:29.500Z",
        counters: routeCounters({ accepted: 4, delivered: 3 }),
      },
    ],
    messages: [
      {
        sequence: 1,
        timestamp: "2026-08-08T11:59:55.000Z",
        messageIdSuffix: "a1b2c3",
        direction: "claude_to_codex",
        sourceAlias: "claude-advisor@this-mac",
        targetAlias: "codex-reviewer@this-mac",
        state: "queued",
        bytes: 128,
        hopCount: 0,
      },
      {
        sequence: 2,
        timestamp: "2026-08-08T11:59:57.000Z",
        messageIdSuffix: "a1b2c3",
        direction: "claude_to_codex",
        sourceAlias: "claude-advisor@this-mac",
        targetAlias: "codex-reviewer@this-mac",
        state: "delivered",
        latencyMs: 2_000,
        bytes: 128,
        hopCount: 0,
      },
      {
        sequence: 3,
        timestamp: "2026-08-08T11:59:58.000Z",
        messageIdSuffix: "c0ffee",
        direction: "codex_to_claude",
        sourceAlias: "codex-reviewer@this-mac",
        targetAlias: "claude-advisor@this-mac",
        state: "unconfirmed",
        latencyMs: 3_000,
        bytes: 96,
        hopCount: 0,
        safeErrorCode: "CLAUDE_RECEIPT_UNCONFIRMED",
      },
      {
        sequence: 4,
        timestamp: "2026-08-08T11:59:59.000Z",
        messageIdSuffix: "decaf0",
        direction: "codex_to_claude",
        sourceAlias: "codex-reviewer@this-mac",
        targetAlias: "claude-advisor@this-mac",
        state: "ambiguous",
        latencyMs: 4_000,
        bytes: 64,
        hopCount: 0,
        safeErrorCode: "CLAUDE_WRITE_AMBIGUOUS",
      },
    ],
    accounting: {
      accepted: 6,
      duplicates: 0,
      delivered: 4,
      unconfirmed: 1,
      failed: 0,
      ambiguous: 1,
      expired: 0,
      cancelled: 0,
      abandoned: 0,
      rejected: 0,
      bytesAccepted: 416,
      queuedBytes: 192,
    },
    alerts: [],
    truncation: {
      connectors: 0,
      availablePeers: 0,
      routes: 0,
      messages: 0,
      alerts: 0,
    },
  };
}

export function routeCounters(
  overrides: Partial<GatewayPublicSnapshot["routes"][number]["counters"]> = {},
): GatewayPublicSnapshot["routes"][number]["counters"] {
  return {
    accepted: 0,
    delivered: 0,
    unconfirmed: 0,
    failed: 0,
    ambiguous: 0,
    expired: 0,
    cancelled: 0,
    abandoned: 0,
    rejected: 0,
    bytesAccepted: 0,
    ...overrides,
  };
}
