// Copied from OpenAI Codex ad931a4:
// codex-rs/app-server-protocol/schema/typescript/v2/ThreadSortKey.ts
// Generated by ts-rs. Keep these native wire values independent of Embassy.
export type ThreadSortKey = "created_at" | "updated_at" | "recency_at" | "section_position";
