// Copied from OpenAI Codex a5290028:
// codex-rs/app-server-protocol/schema/typescript/v2/{ThreadLoadedListParams,
// ThreadLoadedListResponse,ThreadReadParams}.ts
// Generated by ts-rs. Keep these native wire values independent of Embassy.
export type ThreadLoadedListParams = { cursor?: string | null; limit?: number | null };
export type ThreadLoadedListResponse = { data: Array<string>; nextCursor: string | null };
export type ThreadReadParams = { threadId: string; includeTurns?: boolean };
